---
name: Release Bmeme PHP container images
on:
  push:
    branches:
      - "main"

env:
  registry: docker.io
  repository: bmeme/php

jobs:

  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - 
        name: Checkout to repository
        uses: actions/checkout@v3
      -
        name: Set matrix data
        id: set-matrix
        run: echo "matrix=$(jq -c . < ./config.json)" >> $GITHUB_OUTPUT
  
  build:
    name: Build and push Bmeme PHP container images using Docker
    runs-on: ubuntu-latest
    needs: configure
    strategy:
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
    steps:
      - 
        name: Check out the codebase.
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build images
        id: build
        env:
          DOCKERFILE: ${{ matrix.php_pretty_version }}/${{ matrix.os_version }}/${{ matrix.php_type }}/Dockerfile
          PRETTY_TAG: ${{ matrix.php_pretty_version }}-${{ matrix.php_type }}-${{ matrix.os_version }}
          MAIN_TAG: ${{ matrix.name }}
        run: |
          {
            docker build \
              -t ${{ env.registry }}/${{ env.repository }}:${MAIN_TAG} \
              -t ${{ env.registry }}/${{ env.repository }}:${PRETTY_TAG} \
              -f ${DOCKERFILE} .; \
            
            if ${{ matrix.latest }}; then
              docker build -t ${{ env.registry }}/${{ env.repository }}:latest \
                 -f ${DOCKERFILE} .; \
            fi
          }
      - 
        name: Push images to Docker Hub
        id: push
        env:
          DOCKERFILE: ${{ matrix.php_pretty_version }}/${{ matrix.os_version }}/${{ matrix.php_type }}/Dockerfile
          PRETTY_TAG: ${{ matrix.php_pretty_version }}-${{ matrix.php_type }}-${{ matrix.os_version }}
          MAIN_TAG: ${{ matrix.name }}
        run: |
          {
            docker push ${{ env.registry }}/${{ env.repository }}:${MAIN_TAG}; \
            docker push ${{ env.registry }}/${{ env.repository }}:${PRETTY_TAG}; \
            if ${{ matrix.latest }}; then
              docker push ${{ env.registry }}/${{ env.repository }}:latest;
            fi
          }
